vim.g.mapleader = ' '

---vim.opt.list listchars = tab:»·,trail:·
---vim.opt.listchars=tab:>\ ,trail:-,extends:>,precedes:<,nbsp:+
--vim.opt.diffopt += context:3
--vim.opt.display += lastline
--vim.opt.fillchars+=vert:▏
--vim.opt.iskeyword+=-
--vim.opt.shortmess+=I
--vim.opt.shortmess+=c

vim.opt.cmdheight      = 2
vim.opt.colorcolumn    = '+1'
vim.opt.completeopt    = {'menuone', 'noinsert', 'noselect'}
vim.opt.confirm        = true
vim.opt.cursorline     = true
vim.opt.expandtab      = true
vim.opt.foldenable     = false
vim.opt.foldmethod     = 'indent'
vim.opt.foldnestmax    = 3
vim.opt.hidden         = true
vim.opt.hlsearch       = true
vim.opt.ignorecase     = true
vim.opt.incsearch      = true
vim.opt.joinspaces     = false
vim.opt.lazyredraw     = true
vim.opt.list           = true
vim.opt.modeline       = false
vim.opt.mouse          = 'a'
vim.opt.number         = true
vim.opt.pumblend       = 5
vim.opt.pumheight      = 10
vim.opt.relativenumber = true
vim.opt.scrolljump     = 5
vim.opt.scrolloff      = 4
vim.opt.shell          = '/usr/bin/sh'
vim.opt.shiftround     = true
vim.opt.shiftwidth     = 2
vim.opt.shortmess      = 'atToOI'
vim.opt.showbreak      = " "
vim.opt.showcmd        = false
vim.opt.showmode       = false
vim.opt.showtabline    = 0
vim.opt.sidescroll     = 1
vim.opt.sidescrolloff  = 8
vim.opt.signcolumn     = 'auto:2'
vim.opt.smartcase      = true
vim.opt.smartindent    = true
vim.opt.splitbelow     = true
vim.opt.splitright     = true
vim.opt.swapfile       = false
vim.opt.synmaxcol      = 120
vim.opt.tabstop        = 2
vim.opt.termguicolors  = true
vim.opt.textwidth      = 80
vim.opt.updatetime     = 300
vim.opt.wildmode       = {'longest', 'full'}
vim.opt.winblend       = 5
vim.opt.wrap           = false
vim.opt.writebackup    = true
